// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TCPRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TCPMESSAGE {

  /// <summary>Holder for reflection information generated from TCPRequest.proto</summary>
  public static partial class TCPRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for TCPRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TCPRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBUQ1BSZXF1ZXN0LnByb3RvEgtUQ1BfTUVTU0FHRRoKc2VjMS5wcm90byKj",
            "AQoHUGF5bG9hZBImCgR0eXBlGAEgASgOMhguVENQX01FU1NBR0UuTWVzc2Fn",
            "ZVR5cGUSGgoEc2VjMRgCIAEoCzIMLlNlYzFQYXlsb2FkEhMKC3JlbGF5TnVt",
            "YmVyGAMgASgNEisKCnJlbGF5U3RhdGUYBCABKA4yFy5UQ1BfTUVTU0FHRS5S",
            "ZWxheVN0YXRlEhIKClN0cmluZ0RhdGEYBSABKAkqJQoKUmVsYXlTdGF0ZRIL",
            "CgdUdXJuT2ZmEAASCgoGVHVybk9uEAEqTgoLTWVzc2FnZVR5cGUSFgoSTmV3",
            "U2VjdXJpdHlTZXNzaW9uEAASFgoSU3dpdGNoUmVsYXlSZXF1ZXN0EAESDwoL",
            "UGF5bG9hZERhdGEQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Sec1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::TCPMESSAGE.RelayState), typeof(global::TCPMESSAGE.MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TCPMESSAGE.Payload), global::TCPMESSAGE.Payload.Parser, new[]{ "Type", "Sec1", "RelayNumber", "RelayState", "StringData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RelayState {
    [pbr::OriginalName("TurnOff")] TurnOff = 0,
    [pbr::OriginalName("TurnOn")] TurnOn = 1,
  }

  public enum MessageType {
    [pbr::OriginalName("NewSecuritySession")] NewSecuritySession = 0,
    [pbr::OriginalName("SwitchRelayRequest")] SwitchRelayRequest = 1,
    [pbr::OriginalName("PayloadData")] PayloadData = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Payload : pb::IMessage<Payload>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Payload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TCPMESSAGE.TCPRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payload(Payload other) : this() {
      type_ = other.type_;
      sec1_ = other.sec1_ != null ? other.sec1_.Clone() : null;
      relayNumber_ = other.relayNumber_;
      relayState_ = other.relayState_;
      stringData_ = other.stringData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payload Clone() {
      return new Payload(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::TCPMESSAGE.MessageType type_ = global::TCPMESSAGE.MessageType.NewSecuritySession;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TCPMESSAGE.MessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "sec1" field.</summary>
    public const int Sec1FieldNumber = 2;
    private global::Sec1Payload sec1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Sec1Payload Sec1 {
      get { return sec1_; }
      set {
        sec1_ = value;
      }
    }

    /// <summary>Field number for the "relayNumber" field.</summary>
    public const int RelayNumberFieldNumber = 3;
    private uint relayNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RelayNumber {
      get { return relayNumber_; }
      set {
        relayNumber_ = value;
      }
    }

    /// <summary>Field number for the "relayState" field.</summary>
    public const int RelayStateFieldNumber = 4;
    private global::TCPMESSAGE.RelayState relayState_ = global::TCPMESSAGE.RelayState.TurnOff;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TCPMESSAGE.RelayState RelayState {
      get { return relayState_; }
      set {
        relayState_ = value;
      }
    }

    /// <summary>Field number for the "StringData" field.</summary>
    public const int StringDataFieldNumber = 5;
    private string stringData_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringData {
      get { return stringData_; }
      set {
        stringData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Payload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Payload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Sec1, other.Sec1)) return false;
      if (RelayNumber != other.RelayNumber) return false;
      if (RelayState != other.RelayState) return false;
      if (StringData != other.StringData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::TCPMESSAGE.MessageType.NewSecuritySession) hash ^= Type.GetHashCode();
      if (sec1_ != null) hash ^= Sec1.GetHashCode();
      if (RelayNumber != 0) hash ^= RelayNumber.GetHashCode();
      if (RelayState != global::TCPMESSAGE.RelayState.TurnOff) hash ^= RelayState.GetHashCode();
      if (StringData.Length != 0) hash ^= StringData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::TCPMESSAGE.MessageType.NewSecuritySession) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (sec1_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sec1);
      }
      if (RelayNumber != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RelayNumber);
      }
      if (RelayState != global::TCPMESSAGE.RelayState.TurnOff) {
        output.WriteRawTag(32);
        output.WriteEnum((int) RelayState);
      }
      if (StringData.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StringData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::TCPMESSAGE.MessageType.NewSecuritySession) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (sec1_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sec1);
      }
      if (RelayNumber != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RelayNumber);
      }
      if (RelayState != global::TCPMESSAGE.RelayState.TurnOff) {
        output.WriteRawTag(32);
        output.WriteEnum((int) RelayState);
      }
      if (StringData.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StringData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::TCPMESSAGE.MessageType.NewSecuritySession) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (sec1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sec1);
      }
      if (RelayNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RelayNumber);
      }
      if (RelayState != global::TCPMESSAGE.RelayState.TurnOff) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RelayState);
      }
      if (StringData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Payload other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::TCPMESSAGE.MessageType.NewSecuritySession) {
        Type = other.Type;
      }
      if (other.sec1_ != null) {
        if (sec1_ == null) {
          Sec1 = new global::Sec1Payload();
        }
        Sec1.MergeFrom(other.Sec1);
      }
      if (other.RelayNumber != 0) {
        RelayNumber = other.RelayNumber;
      }
      if (other.RelayState != global::TCPMESSAGE.RelayState.TurnOff) {
        RelayState = other.RelayState;
      }
      if (other.StringData.Length != 0) {
        StringData = other.StringData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::TCPMESSAGE.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (sec1_ == null) {
              Sec1 = new global::Sec1Payload();
            }
            input.ReadMessage(Sec1);
            break;
          }
          case 24: {
            RelayNumber = input.ReadUInt32();
            break;
          }
          case 32: {
            RelayState = (global::TCPMESSAGE.RelayState) input.ReadEnum();
            break;
          }
          case 42: {
            StringData = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::TCPMESSAGE.MessageType) input.ReadEnum();
            break;
          }
          case 18: {
            if (sec1_ == null) {
              Sec1 = new global::Sec1Payload();
            }
            input.ReadMessage(Sec1);
            break;
          }
          case 24: {
            RelayNumber = input.ReadUInt32();
            break;
          }
          case 32: {
            RelayState = (global::TCPMESSAGE.RelayState) input.ReadEnum();
            break;
          }
          case 42: {
            StringData = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
